% rd_modifyBrainSliceMaps.m

% brainSliceMaps is a 1xnSlices cell generated by rd_plotTopographicData2SatFn.m

%% setup
subject = 'AV';
hemi = 2;
mapName = 'betaP';
plotFormat = 'singleRow'; % 'figPerSlice','singleRow'
aspectRatio = [1 1 1]; %[1.575 1.75 1]; % use voxel size (for coronal, [Z X Y])
dimToSlice = 2; % 1=Sag, 2=Cor, 4=Ax
sliceTitleOn = 0;
saveFigs = 1;

%% generate the original map
switch mapName
    case 'betaM-P'
        weights = [.5 -.5];
    case 'betaM'
        weights = [1 0];
    case 'betaP'
        weights = [0 1];
    otherwise
        error('mapName not recognized')
end
brainSliceMaps = rd_plotTopographicData2SatFn(hemi,'all','full',weights,mapName,0,0);

%% modify the map
% create one black row and one black column
[rowSize colSize rgbSize] = size(brainSliceMaps{1});
blackRow = zeros(1, colSize, rgbSize);
blackCol = zeros(rowSize, 1, rgbSize);

switch subject
    case 'AV'
        % for AV, add rows
        nSlices = numel(brainSliceMaps);
        for iSlice = 1:nSlices
            newSliceMaps{iSlice} = cat(1, blackRow, brainSliceMaps{iSlice}, blackRow);
            %     newSliceMaps{iSlice} = cat(1, brainSliceMaps{iSlice}, blackRow);
            %     newSliceMaps{iSlice} = cat(1, blackRow, brainSliceMaps{iSlice});
        end
    case 'RD'
        % for RD, add columns
        nSlices = numel(brainSliceMaps);
        for iSlice = 1:nSlices
            newSliceMaps{iSlice} = cat(2, blackCol, brainSliceMaps{iSlice});
        end
    otherwise
        error('subject not recognized')
end
    
%% plot modified map
f1 = figure('name',mapName);
for iSlice = 1:nSlices

    % get brain slice map
    brainSliceMap = newSliceMaps{iSlice};
    
    % show slice with colored map
    switch plotFormat
        case 'singleRow' % plots slices in reverse order
            nPlotRows = 1;
            nPlotCols = nSlices;
            subplot(nPlotRows, nPlotCols, nPlotCols+1-iSlice)
        case 'figPerSlice'
            f(iSlice) = figure('name',sprintf('%s slice %d',mapName, iSlice));
        otherwise
            error('plotFormat not recognized')
    end
    
    image(brainSliceMap)
    
    if sliceTitleOn
        if dimToSlice==4
            title(['Slice ' num2str(slices(iSlice))])
        else
            title(['Slice ' num2str(iSlice)])
        end
    end
    axis off
    axis tight
    
    % set aspect ratio
    daspect(aspectRatio)
end

%% save individual slices
if saveFigs
    fileBase = sprintf('figures/%s_%s', subject, mapName);
    switch plotFormat
        case 'singleRow'
            print(f1,'-dpng','-r300', sprintf('%s_row', fileBase))
        case 'figPerSlice'
            
            for iSlice = 1:nSlices
                print(f(iSlice),'-dpng','-r300', sprintf('%s_slice%d', fileBase, iSlice))
            end
        otherwise
            error('plotFormat not recognized')
    end
end

